spring.application.name=LoginLogoutDemo

#Adding Db connection related statements
spring.datasource.url = jdbc:postgresql://localhost:5432/hospitaldb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#port no. : 5432 , name of the user : postgres password: root name of Db : hospitaldb

