version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hospital_postgres
    environment:
      POSTGRES_DB: hospitaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: loginlogout_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: